# Generated by Django 5.1.2 on 2024-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('beats_per_minute', models.IntegerField()),
                ('time_signature', models.CharField(max_length=10)),
                ('accuracy', models.FloatField()),
                ('longest_on_beat', models.DurationField()),
            ],
        ),
    ]
